package com.multimediachat.app.im.plugin;

import java.util.Map;

public interface ImPlugin {
    /**
     * Gets a map of branding resources for the provider. The keys are defined
     * in {@link BrandingResourceIDs}.
     * The values are the resource identifiers generated by the aapt tool.
     * 
     * @return The map of branding resources.
     */
    Map<Integer, Integer> getResourceMap();

    /**
     * Gets the configuration for the provider. The keys MUST match the values
     * defined in {@link ImConfigNames} and {@link ImpsConfigNames}
     * 
     * @return the configuration for the provider.
     */
    Map<String, String> getProviderConfig();
}
